name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v4

    - name: Unzip project
      run: |
        Expand-Archive -Path ManejoClientes_GO.zip -DestinationPath project
        Copy-Item Icon.png project/ManejoClientes_GO/src/Icon.png

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install Fyne
      run: |
        go install fyne.io/fyne/v2/cmd/fyne@v2.4.3

    - name: Tidy dependencies
      working-directory: project/ManejoClientes_GO/src
      run: |
        go mod tidy

    - name: Build EXE
      working-directory: project/ManejoClientes_GO/src/cmd/manejoclientes
      run: |
        fyne package -os windows -name ManejoClientes -icon ""

    - name: Save executable
      uses: actions/upload-artifact@v4
      with:
        name: ManejoClientes-Windows
        path: project/ManejoClientes_GO/src/ManejoClientes.exe
